# =============================================================================
# R-Type Level Configuration
# =============================================================================

[level]
id = "level2-custom"
name = "MonPtit2"
background = "Labs"
scroll_speed = 50.0
boss = "boss_1"
next_level = "level3.toml"
level_music = "ExploreMusic"

# -----------------------------------------------------------------------------
# Wave 1
# -----------------------------------------------------------------------------
[[wave]]
number = 1
spawn_delay = 0.8

[[wave.spawn]]
enemy = "basic"
delay = 0.0
count = 1


