# Music Réferences
[Music]
MainMenu = "audio/mainMenuMusic.mp3"
Game = "audio/gameMusic.mp3"
Settings = "audio/settingsMusic.mp3"
GameOver = "audio/gongGameOver.mp3"

[SFX]
HoverButton = "audio/hoverButton.mp3"
ClickButton = "audio/clickButton.mp3"
Laser = "audio/laserSound.mp3"
PlayerDeath = "audio/playerDeath.mp3"
PlayerSpawn = "audio/playerSpawn.mp3"
EnemyDeath = "audio/enemyDeath.mp3"
EnemySpawn = "audio/enemySpawn.mp3"

# Textures Réferences
[Textures]
Player = "img/playerTexture.gif"
Enemy = "img/bdosTexture.gif"
# Backougrnd assets
Background = "img/bgMainMenu.png"
Sun = "img/sun.png"
BigAsteroids = "img/bigAsteroids.png"
SmallAsteroids = "img/smallAsteroids.png"
FstPlanAsteroids = "img/fstPlanAsteroids.png"
SndPlanAsteroids = "img/sndPlanAsteroids.png"
Planet1 = "img/planet1.png"
Planet2 = "img/planet2.png"
Planet3 = "img/planet3.png"
AstroVessel = "img/astroVessel.png"
# Projectile assets
MissileLaser = "img/missileLaser.gif"

[Fonts]
MainFont = "fonts/Orbitron-VariableFont_wght.ttf"
TitleFont = "fonts/Audiowide-Regular.ttf"